Add ability to ignore specific paths
aschmelyun/larametrics pull request #26
Opened 2018-10-31 14:59 UTC by nowendwell

This adds the ability to specify paths to skip request logging.

2018-10-31 20:18 UTC, johannesschobel requested changes

2018-10-31 20:18 UTC, johannesschobel commented on src/LarametricsRouteServiceProvider.php
> +                //dd($routeMatched->route);
i think, all `dd()` and comments should be removed..

2018-11-01 02:09 UTC, josteph commented
@nowendwell Wildcard support?

2018-11-01 02:32 UTC, nowendwell commented
@josteph Yep. It uses the Request::is() which in turn uses the Str::is() function which does a preg_match. 

Tested using '*r*' and then tried 'password/reset' and 'register' and both were skipped.

2018-11-04 10:36 UTC, merged

2018-11-04 10:37 UTC, aschmelyun commented
Super handy feature, thanks for getting it out!

2018-11-06 11:28 UTC, tanmuhittin commented on src/config/larametrics.php
> +
Should we have an option for method type of request? An array similar to below could be used.
`'requestsToSkip'=>[
  'GET'=>'*',
  'POST'=>['login','comment']
]`
Or maybe we can use route names and route group names for this action.

2018-11-06 13:15 UTC, johannesschobel commented
I would go for the route-name approach, as I think this would be more fool-proof..